### ISSUE TITLE
在 Android 11 Beta 版中无法正常工作

### ISSUE THREAD

**Issue by cccClyde** [Magisk-Modules-Repo/riru_location_report_enabler#1]
Android 11 Beta 1，Google Pixel 4 XL，riru core v21.2

Location Report Enabler 模块开启后位置历史记录能够正常开启，但负一屏提示无法登录到 Google 账号，同时系统的定位似乎也会受到干扰，表现为深色主题无法再自动获取日出日落时间并自动切换。

**Comment by RikkaW** [comment]
其实这个已经弃坑了（
定位受到干扰应该是乱甩锅
